name: Get Code Scanner Results

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Repo'
        default: 'WebGoat'
        required: true
jobs:
    
  # Job Name
  get-scanner-results:

    runs-on: ubuntu-latest

    steps:
      
      # Get GHAS code scanner results
      - name: GHAS code scanner results
        id: ghasCodeScannerResults
        uses: fjogeleit/http-request-action@v1.10.0
        with:
          url: "https://api.github.com/repos/eng-github-tester-01/WebGoat/code-scanning/analyses"
          timeout: 60000
          method: 'GET'
          bearerToken: ${{ secrets.PAT_TOKEN }}
      - name: Show Response
        run: |
          echo ${{ steps.ghasCodeScannerResults.outputs.response }}
          echo ${{ steps.ghasCodeScannerResults.outputs.headers }}
          echo ${{ fromJson(steps.ghasCodeScannerResults.outputs.response)[0].url }}  
